services:
  postgres:
    image: postgres:15
    container_name: postgres-zonapiloto
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zonapiloto_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  auth-service:
    build: ./zonapiloto_back/services/auth-service
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SUPERADMIN_USERNAME: ${SUPERADMIN_USERNAME}
      SUPERADMIN_PASSWORD: ${SUPERADMIN_PASSWORD}

    expose:
      - "5001"
    networks:
      - zonapiloto_net

  information-service:
    build: ./zonapiloto_back/services/information-service
    container_name: information-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    expose:
      - "5002"
    networks:
      - zonapiloto_net

  profile-service:
    build: ./zonapiloto_back/services/profile-service
    container_name: profile-service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    expose:
      - "5003"
    networks:
      - zonapiloto_net

  gateway:
    build: ./zonapiloto_back/gateway
    container_name: gateway
    restart: unless-stopped
    depends_on:
      auth-service:
        condition: service_started
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SERVICES_URLS: >
        auth-service=http://auth-service:5001/actuator/health,
        information-service=http://information-service:5002/actuator/health,
        profile-service=http://profile-service:5003/actuator/health,

    expose:
      - "5000"
    networks:
      - zonapiloto_net
      - frontend_net

  frontend:
    build:
      context: ./zonapiloto_front
      dockerfile: Dockerfile.dev
      args:
        VITE_API_BASE_URL: "http://127.0.0.1/api"
    container_name: zonapiloto-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - frontend_net
    depends_on:
      - gateway

networks:
  zonapiloto_net:
    driver: bridge
  frontend_net:
    driver: bridge

volumes:
  postgres_data:
