version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-zonapiloto
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zonapiloto
    ports:
      - "3306:3306"
    volumes:
      - zonapiloto_db:/var/lib/mysql
    networks:
      - zonapiloto_net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  app:
    build: .
    container_name: spring-zonapiloto
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/zonapiloto?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"
    networks:
      - zonapiloto_net

networks:
  zonapiloto_net:

volumes:
  zonapiloto_db:
